Pull in upstream updates
cisagov/lcgit pull request #4
Opened 2022-03-06 02:22 UTC by mcdonnnj

#  #

## 🗣 Description ##

This pull request updates this repository with the latest in [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library). This includes a configuration for [cisagov/action-lineage](https://github.com/cisagov/action-lineage) so it will get future updates automatically.

## 💭 Motivation and context ##

I was reminded of this project this week and noticed that it was woefully out of date.

## 🧪 Testing ##

Automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

2022-03-06 02:40 UTC, jsf9k approved these changes
Thanks for bringing this one back to life, necromancer!

2022-03-07 15:01 UTC, dav3r requested changes
Please see the one small thing that I mentioned, then we're good to go.  Thanks for shepherding this lost lamb back to the flock! 🐑

2022-03-07 15:01 UTC, dav3r commented on bump_version.sh
> +VERSION_FILE=src/example/_version.py
```suggestion
VERSION_FILE=src/lcgit/_version.py
```

2022-03-07 15:09 UTC, mcdonnnj commented on bump_version.sh
> +VERSION_FILE=src/example/_version.py
Ah! Missed that one, thanks!

2022-03-07 15:13 UTC, dav3r approved these changes
🤘

2022-03-07 17:29 UTC, merged